
### CREATE USER test1
POST http://localhost:5055/api/auth/register
Content-Type: application/json

{
    "name": "Harriot Dibble",
    "email": "hdibble@oraxys.abc",
    "password": "is this a password?"
}


### LOGIN AS test1
POST http://localhost:5055/api/auth/login
Content-Type: application/json

{
    "email": "hdibble@oraxys.abc",
    "password": "is this a password?"
}

### POST /api/auth/register AS jeremiah
POST http://localhost:5055/api/auth/register
Content-Type: application/json

{
    "email": "jfisher@tsitp.com",
    "name": "Jeremiah Fisher",
    "password": "isabelle"
}

### GET /tasks AS jeremiah
GET http://localhost:5055/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5N2Q5NTkzNi0yNTBlLTQ0ZDUtYTBiOS1mNThlZWM5OTRmNGEiLCJlbWFpbCI6ImpmaXNoZXJAdHNpdHAuY29tIiwianRpIjoiMzdhMDk0ZWEtOWI5MC00Yjg2LThiMWYtMWM2ZTk4YjYyZWVkIiwibmFtZSI6IkplcmVtaWFoIEZpc2hlciIsIm5iZiI6MTc5MTU1MDExMiwiZXhwIjoxNzkxNTUzNzEyLCJpYXQiOjE3OTE1NTAxMTIsImlzcyI6IlRhc2tBcGkiLCJhdWQiOiJUYXNrQXBpQ2xpZW50In0.mAVHGz0mSK_q17BWYO_9Fu5xb3P2Y-PSpWPlIhkAuJA

### GET /tasks AS harriot
GET http://localhost:5055/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZjAyZTJiOC0wMGMyLTQ0NzQtYjMxMC1iN2U5OTk0YzYzNGQiLCJlbWFpbCI6ImhkaWJibGVAb3JheHlzLmFiYyIsImp0aSI6ImQ0YTMwM2VmLTg3MzMtNDFjYi04NGNhLWI4NTM2MzgwMzdhOCIsIm5hbWUiOiJIYXJyaW90IERpYmJsZSIsIm5iZiI6MTc5MTU1MDU5OCwiZXhwIjoxNzkxNTU0MTk4LCJpYXQiOjE3OTE1NTA1OTgsImlzcyI6IlRhc2tBcGkiLCJhdWQiOiJUYXNrQXBpQ2xpZW50In0.pYwED1VYM5bdMHYpInjR5LLekIoEWGOwHsoE6nVuPxw

### GET non-restricted routes
GET http://localhost:5055/tasksDeep

### GET /tasks without Authorization [401 Unauthorized]
GET http://localhost:5055/tasks
